// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCymdhAtLSgpv82nFysZ83ZN63r7Ejv8O4',
    appId: '1:512818372133:web:4270faa3faca8e24fc69cc',
    messagingSenderId: '512818372133',
    projectId: 'imagineai-8def0',
    authDomain: 'imagineai-8def0.firebaseapp.com',
    storageBucket: 'imagineai-8def0.appspot.com',
    measurementId: 'G-M2SSX32SK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4agumen0moiirzAywymu3LDkpRzyu4I8',
    appId: '1:512818372133:android:44d60e7970a9343dfc69cc',
    messagingSenderId: '512818372133',
    projectId: 'imagineai-8def0',
    storageBucket: 'imagineai-8def0.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCymdhAtLSgpv82nFysZ83ZN63r7Ejv8O4',
    appId: '1:512818372133:web:d0d1371e21e43f30fc69cc',
    messagingSenderId: '512818372133',
    projectId: 'imagineai-8def0',
    authDomain: 'imagineai-8def0.firebaseapp.com',
    storageBucket: 'imagineai-8def0.appspot.com',
    measurementId: 'G-46BP0PTC97',
  );
}
